### ISSUE TITLE
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) no such table

### ISSUE THREAD

**Issue by amirraouf** [italomaia/flask-empty#24] opened 2018-07-22 13:20 UTC
Settings are working well with normal app but while testing it raises this error

I checked all the settings and even the database, all is fine, database testing created, all is working however this error is up

I follow the blog example tree for test package.

**Comment by italomaia** [comment] 2018-10-02 20:44
Interesting. Will take a look this week.

**Comment by italomaia** [comment] 2018-10-04 19:12
Hey @amirraouf could you give me some more details about your error? Which command did you run? no such table happens when you did not create the table. Did you run the migrate command?

**Comment by italomaia** [comment] 2018-12-30 22:56
Hello @amirraouf 
I'm closing the issue until further info is provided by you as I cannot reproduce the problem you had. Thanks for your interest.

**Closed by italomaia** 2018-12-30 22:56 UTC
